# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c364e1acc08cb5bf90e269a3eb0b070c7a97c495377ba99428f82b75e9037e8376e1c3215b03b4a2fa6cd262b8b9267bd8565dd18eba32aa56163a68cf92fd4

test:
  secret_key_base: a06699c2382f79deced34203da623bf0ce21dcffbc6c0874f1caea67b28514fef8ae84015f73f1484e68f12b06cda173bbc6a22eb452793b7f83adbf6a2cc093

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
